name: test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
 test:
    runs-on: ubuntu-latest

    steps:
     - name: 'hello word'
       run: echo "hello word"
     - name: fecha
       run: date
     - name: Muestrame el contenido del directorio
       run: ls -la